name: ice
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - cftime
  - cmocean
  - esmf
  - esmpy
  - geopandas
  - geos
  - hdf4
  - hdf5
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf-fortran
  - notebook
  - numpy
  - pandas
  - pillow
  - proj
  - pyproj
  - rasterio
  - rioxarray
  - scipy
  - shapely
  - tqdm
  - xarray
  - xesmf